a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfanumerico? ', a.isalnum())
print('É um alfabético? ', a.isalpha())
print('Está em maiúscula? ', a.isupper())
print('Está em miniúscula? ', a.islower())
print('Está capitalizado? ', a.istitle())
